#spring.application.name=accounts


server:
  port: 8090

spring:
  application:
    name: "loans"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3308/loansdb
    username: root
    password: root
  sql:
    init:
      mode: always
  jpa:
    show-sql: true

  config:
    import: "optional:configserver:http://localhost:8071"



management:
  endpoints:
    web:
      exposure:
        include: "*"