#spring.application.name=accounts


server:
  port: 8090

spring:
  application:
    name: "loans"
  profiles:
    active: "prod"
  datasource:
#    url: jdbc:mysql://localhost:3308/loansdb
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: root
    password: root
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: "optional:configserver:http://localhost:8071"



management:
  endpoints:
    web:
      exposure:
        include: "*"