spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"


loans:
  message: "Welcome to Atul loans related local APIs "
  contactDetails:
    name: "Anu - Project Manager"
    email: "anu@test.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345