
build:
  version: "3.0"



cards:
  message: "Welcome to Atul loans related local APIs "
  contactDetails:
    name: "Atul - Developer"
    email: "atul@test.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345

