
spring:
  application:
    name: "configserver"
  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/iatulb/my-microservices.git"
          default-label: "master"
          timeout: 5
          clone-on-start: true
          force-pull: true
#        native:
##          search-locations: "classpath:/config/"
#          search-locations: "file:///D://work_dsi//Projects//Learning//my-microservices//config"

server:
  port: 8071


